server:
  port: 8091

spring:
  application:
    name: ci-aliclient
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8111/eureka/
      
logging:
  file: logs/${spring.application.name}.log